//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("SccmTools provides various SCCM 2012 commands")]
[assembly: AssemblyCompany("github.com.trondr")]
[assembly: AssemblyProduct("SccmTools")]
[assembly: AssemblyCopyright("Copyright © github.com.trondr 2016")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.15339.2.5d4336b")]
[assembly: AssemblyVersion("1.0.15339.2")]
[assembly: AssemblyFileVersion("1.0.15339.2")]


