//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("SccmTools creates a new solution by resolving a selected default " +
    "or user defined template solution.")]
[assembly: AssemblyCompany("github.com/trondr")]
[assembly: AssemblyProduct("SccmTools")]
[assembly: AssemblyCopyright("Copyright © <github.com/trondr> 2014")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("1.0.14274.f2d2bc4")]
[assembly: AssemblyVersion("1.0.14274.1")]
[assembly: AssemblyFileVersion("1.0.14274.1")]


