//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("SccmTools provides a command for creating an SCCM 2012 application from a package" +
    " definition file.")]
[assembly: AssemblyCompany("github.com.trondr")]
[assembly: AssemblyProduct("SccmTools.Tests")]
[assembly: AssemblyCopyright("Copyright © github.com.trondr 2017")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.17046.5.c47980e")]
[assembly: AssemblyVersion("1.0.17046.5")]
[assembly: AssemblyFileVersion("1.0.17046.5")]


