//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("SccmTools provides various commands for Sccm 2012 interaction")]
[assembly: AssemblyCompany("github.com/trondr")]
[assembly: AssemblyProduct("SccmTools.Library")]
[assembly: AssemblyCopyright("Copyright © github.com/trondr 2015")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.15092.0.0582190")]
[assembly: AssemblyVersion("1.0.15092.0")]
[assembly: AssemblyFileVersion("1.0.15092.0")]


